workflows:
  unsigned-ios-build:
    name: Unsigned iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      # cocoapods: default  # removed because no pods
    scripts:
      # Removed CocoaPods step since no Podfile
      - name: Build unsigned IPA
        script: |
          xcodebuild \
            -project "$CM_BUILD_DIR/TicTacPro.xcodeproj" \
            -scheme "TicTacPro" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/build/TicTacPro.xcarchive" \
            clean archive

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/TicTacPro.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist"
    artifacts:
      - build/ios/ipa/*.ipa
