workflows:
  unsigned-ios-build:
    name: Unsigned iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Create ExportOptions.plist
        script: |
          cat > "$CM_BUILD_DIR/ExportOptions.plist" << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF

      - name: Unity build iOS project
        script: |
           "C:/Program Files/Unity/Hub/Editor/2022.3.21f1/Editor/Unity.exe" \
            -batchmode \
            -projectPath "$CM_BUILD_DIR" \
            -executeMethod YourBuildScript.BuildiOS \
            -buildTarget iOS \
            -quit \
            -logFile "$CM_BUILD_DIR/unity_build.log"

      - name: Build unsigned IPA
        script: |
          xcodebuild \
            -project "$CM_BUILD_DIR/Unity-iPhone.xcodeproj" \
            -scheme "Unity-iPhone" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/build/Unity-iPhone.xcarchive" \
            clean archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/Unity-iPhone.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist"
    artifacts:
      - build/ios/ipa/*.ipa
