workflows:
  unsigned-ios-build:
    name: Unsigned iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build unsigned IPA
        script: |
          xcodebuild \
            -project "$CM_BUILD_DIR/Unity-iPhone.xcodeproj" \
            -scheme "Unity-iPhone" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/build/Unity-iPhone.xcarchive" \
            clean archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO


          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/Unity-iPhone.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist"
    artifacts:
      - build/ios/ipa/*.ipa
