scripts:
  - name: Build unsigned IPA
    script: |
      xcodebuild \
        -project "$CM_BUILD_DIR/unity-phone.xcodeproj" \
        -scheme "unity-phone" \
        -configuration Release \
        -sdk iphoneos \
        -archivePath "$CM_BUILD_DIR/build/unity-phone.xcarchive" \
        clean archive

      xcodebuild -exportArchive \
        -archivePath "$CM_BUILD_DIR/build/unity-phone.xcarchive" \
        -exportPath "$CM_BUILD_DIR/build/ios/ipa" \
        -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist"
